### ISSUE TITLE
When running npm run keycloak:init the script output refers to the wrong folders

### ISSUE THREAD

**Issue by cjohn001** [aerogear/datasync-starter#335]
Current output:

Copy the following app config into the following files:
- ionic-showcase/client/public/keycloak.json
- ionic-showcase/server/src/config/keycloak.json

Should be corrected in respect of printing both client configurations for 
- voyager-testing-public and
- voyager-testing-bearer

Text should become:

Copy the following app configs into the following files:
Public:
  /datasync-starter/client/public/keycloak.json
  /datasync-starter/server/src/config/keycloak.json
Bearer:
  /datasync-starter/server/website/keycloak.json

**Comment by wtrocki** [comment]
Hi

We decided to always use public client for all configurations while still creating a bearer one so we can swap it. Public will allow us to login to playground and also work with the app. Bearer should be used on the server but that will affect playground
Website folder should always contain public client. 
Happy to discuss this issue but closing provisionally
