### ISSUE TITLE
offix sync with apollo-angular in client app

### ISSUE THREAD

**Issue by cjohn001** [aerogear/datasync-starter#336]
Hello together,
it would be very great, if you could show in an example app how one can use apollo-angular together with offix client in an angular app as well. I assume there is no automatic cache update if a mutation is executed via apollo angular. How would one have to plugin offix than?
Thanks for the great tutorials!

https://github.com/apollographql/apollo-angular

**Comment by wtrocki** [comment]
Hi

DataSync starter is opinionated getting started experience and for this we choose to react. In terms of GraphQL there is no difference for keycloak - all doing http calls that need to use token or cookie. That being said we provide examples for server and any widely available examples can be used outside.

For example: 
https://github.com/mauriciovigolo/keycloak-angular/tree/master/examples
