### ISSUE TITLE
Impossible to login to servers graphql playground (tried with Altair client)

### ISSUE THREAD

**Issue by cjohn001** [aerogear/datasync-starter#337]
Hello,
with the configuration currently provided in the tutorial, it is not possible to access the graphql playground.

Howto try out:
- I used  the provided script in scripts/keycloak/getToken.js to obtain the Authorization header for playground client. I tried with both users, admin and developer.
- I than added the header to altair client and tried to access http://localhost:4000/graphql 
 As a response I only get 403 Access denied

Observation:
I have seen that in keycloak there are two client configurations provided.
-voyager-testing-bearer
-voyager-testing-public
I assume, the public one should be for the react client and the bearer configuration for the graphql server. I configured the server with the bearer. Login via react client than still works (as expected). However, I cannot get the playground to work. Any hints on this?
Thanks for your help!

Update: I could solve the issue now. I would like to recommend some minor changes to the demo app to further improve it. Please replace the following lines from auth.ts

 app.use(keycloak.middleware());
 app.use(graphqlPath, keycloak.protect());

with 

app.use(graphqlPath, keycloak.middleware());

and use @auth directives on the resolvers.

This is responsible for the blocking of the playground.  
Further: One could also add a comment in the reoslvers/schema that @auth and keycloak usage is explained in more detail at https://github.com/aerogear/keycloak-connect-graphql

**Comment by wtrocki** [comment]
Hi 

We have changed our scripts to use public client.
That will be cool feature but it will require us to have Graphback plugin first:
https://github.com/aerogear/graphback/issues/797

**Comment by wtrocki** [comment]
Leaving open till we get that sorted

**Comment by wtrocki** [comment]
Since we have that covered in other issue I'm going to close that one
