### ISSUE TITLE
Capacitor data store

### ISSUE THREAD

**Issue by wtrocki** [aerogear/datasync-starter#372]
Investigate using native storage as oposite to IndexedDB implementation

https://capacitor.ionicframework.com/docs/apis/storage/

**Comment by moulikcipherX** [comment]
Hello @wtrocki , I want to work on the issue.

**Comment by wtrocki** [comment]
That is the project that uses capacitor and offix: https://github.com/aerogear/datasync-starter

This was created as an investigation only, but you can do some prototype

**Comment by moulikcipherX** [comment]
@wtrocki I want to work for the GSoC'20 for the project Data Synchronization. Please suggest to me some issues work on so that I can make the most out of it.

**Comment by wtrocki** [comment]
Wrong project then. Try graphback.dev
